# src/evaluate.py
import numpy as np
from src.config import load_settings
from src.search import QueryEncoder, execute_dynamic_search, parse_user_intent

# =====================================================================
# 1. THE TEST SUITE
# Just write natural queries. The script will grade the results 
# based on how well they match the extracted constraints.
# =====================================================================
TEST_QUERIES = [
    "easy chicken dinner under 45 mins",
    "vegan thanksgiving sides",
    "low carb italian beef skillet",
    "quick healthy breakfast under 15 mins",
    "spicy pork tacos"
]

def score_result_relevance(hit, intent, query_vector):
    source = hit['_source']
    
    # Hard Constraints (No Credit if Violated)
    if intent['max_minutes'] and source['minutes'] > intent['max_minutes']:
        return 0.0
    for diet in intent['dietary_tags']:
        if diet not in source['tags_clean']:
            return 0.0

    # Semantic Proximity
    res_vector = np.array(source.get('recipe_embedding', []))
    q_vector = np.array(query_vector)
    
    # Calculate Cosine Similarity (0 to 1)
    semantic_score = 0.0
    if res_vector.size > 0:
        norm_q = np.linalg.norm(q_vector)
        norm_r = np.linalg.norm(res_vector)
        if norm_q > 0 and norm_r > 0:
            semantic_score = np.dot(q_vector, res_vector) / (norm_q * norm_r)

    # Soft Constraints (Partial Credit Reduction)
    score = semantic_score 
    
    # Apply penalties for missing 'should' intents
    soft_penalty_groups = ["proteins", "courses", "cuisines", "methods", "occasions"]
        
    for group in soft_penalty_groups:
        for tag in intent[group]:
            # Proteins live in ingredients; everything else lives in tags
            if group == "proteins":
                match = any(tag in ing.lower() for ing in source.get('ingredients_clean', []))
            else:
                match = tag in source.get('tags_clean', [])
                
            if not match:
                score *= 0.85

    return score

def evaluate_engine(s):
    print("Initializing Neural-Aware Evaluation Pipeline...")
    encoder = QueryEncoder(s)
    
    metrics = {"precision@5": [], "ndcg@5": []}
    
    print(f"Evaluating {len(TEST_QUERIES)} Test Queries...\n")
    print("-" * 70)
    
    for query in TEST_QUERIES:
        # 1. Capture the vector generated by the encoder during the search
        # Update: We need search.py to return the vector or generate it here.
        # Let's generate it here for the grader so it matches the search logic perfectly.
        intent = parse_user_intent(query)
        query_vector = encoder.encode(query) 
        
        # 2. Execute the search
        results, _ = execute_dynamic_search(s, encoder, query, top_k=5)
        
        if not results:
            print(f"Query: '{query}' -> 0 Results")
            metrics["precision@5"].append(1.0)
            metrics["ndcg@5"].append(1.0)
            continue
            
        # 3. Grade each result using the captured query_vector
        relevance_scores = [score_result_relevance(hit, intent, query_vector) for hit in results]
        
        # 4. Calculate Precision@5 
        # (Since scores are now continuous 0.0-1.0, mean represents avg quality)
        p_at_5 = np.mean(relevance_scores)
        
        # 5. Calculate nDCG@5
        dcg = sum(rel / np.log2(idx + 2) for idx, rel in enumerate(relevance_scores))
        
        # Ideal DCG: Assuming the best possible results have a similarity of 1.0 
        # and satisfy all soft constraints.
        idcg = sum(1.0 / np.log2(idx + 2) for idx in range(len(results)))
        ndcg_at_5 = dcg / idcg if idcg > 0 else 0.0
        
        metrics["precision@5"].append(p_at_5)
        metrics["ndcg@5"].append(ndcg_at_5)
        
        print(f"Query: '{query}'")
        print(f"  -> Precision@5: {p_at_5:.3f} | nDCG@5: {ndcg_at_5:.3f}")
        print(f"  -> Hit Grades : {[round(s, 3) for s in relevance_scores]}") 
        
    print("\n" + "=" * 70)
    print("FINAL SYSTEM PERFORMANCE REPORT")
    print("=" * 70)
    print(f"Mean Precision@5 : {np.mean(metrics['precision@5']):.4f}")
    print(f"Mean nDCG@5      : {np.mean(metrics['ndcg@5']):.4f}")
    print("=" * 70)

if __name__ == "__main__":
    s = load_settings()
    evaluate_engine(s)